// Code generated by entc, DO NOT EDIT.

package task

import (
	"time"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatorID holds the string denoting the creator_id field in the database.
	FieldCreatorID = "creator_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldComplexity holds the string denoting the complexity field in the database.
	FieldComplexity = "complexity"
	// FieldHardDeadline holds the string denoting the hard_deadline field in the database.
	FieldHardDeadline = "hard_deadline"
	// FieldSoftDeadline holds the string denoting the soft_deadline field in the database.
	FieldSoftDeadline = "soft_deadline"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "tasks"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "creator_id"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCreatorID,
	FieldTitle,
	FieldDescription,
	FieldPriority,
	FieldComplexity,
	FieldHardDeadline,
	FieldSoftDeadline,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority string
	// DefaultComplexity holds the default value on creation for the "complexity" field.
	DefaultComplexity string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
)
