version: '3.8'
services:
  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
