// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "priority", Type: field.TypeString, Default: "5"},
		{Name: "complexity", Type: field.TypeString, Default: "5"},
		{Name: "hard_deadline", Type: field.TypeTime, Nullable: true},
		{Name: "soft_deadline", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "123"},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// TaskCreatorColumns holds the columns for the "task_creator" table.
	TaskCreatorColumns = []*schema.Column{
		{Name: "task_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// TaskCreatorTable holds the schema information for the "task_creator" table.
	TaskCreatorTable = &schema.Table{
		Name:       "task_creator",
		Columns:    TaskCreatorColumns,
		PrimaryKey: []*schema.Column{TaskCreatorColumns[0], TaskCreatorColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "task_creator_task_id",
				Columns:    []*schema.Column{TaskCreatorColumns[0]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "task_creator_user_id",
				Columns:    []*schema.Column{TaskCreatorColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TasksTable,
		UsersTable,
		TaskCreatorTable,
	}
)

func init() {
	TaskCreatorTable.ForeignKeys[0].RefTable = TasksTable
	TaskCreatorTable.ForeignKeys[1].RefTable = UsersTable
}
