// Code generated by entc, DO NOT EDIT.

package ent

import (
	"server/internal/ent/schema"
	"server/internal/ent/task"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescIcon is the schema descriptor for icon field.
	taskDescIcon := taskFields[1].Descriptor()
	// task.DefaultIcon holds the default value on creation for the icon field.
	task.DefaultIcon = taskDescIcon.Default.(int)
}
