// Code generated by entc, DO NOT EDIT.

package ent

import (
	"server/internal/ent/schema"
	"server/internal/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[3].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(string)
	// taskDescComplexity is the schema descriptor for complexity field.
	taskDescComplexity := taskFields[4].Descriptor()
	// task.DefaultComplexity holds the default value on creation for the complexity field.
	task.DefaultComplexity = taskDescComplexity.Default.(string)
	// taskDescStatus is the schema descriptor for status field.
	taskDescStatus := taskFields[7].Descriptor()
	// task.DefaultStatus holds the default value on creation for the status field.
	task.DefaultStatus = taskDescStatus.Default.(string)
}
