// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"server/internal/config"
)

// Injectors from wire.go:

func Up(ctx context.Context) (Dependencies, error) {
	configConfig, err := config.New()
	if err != nil {
		return Dependencies{}, err
	}
	dependencies := NewDependencies(configConfig)
	return dependencies, nil
}
