// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"server/internal/config"
	"server/internal/domain/tag"
	"server/internal/domain/task"
	"server/internal/domain/user"
)

import (
	_ "github.com/lib/pq"
	_ "server/internal/docs"
)

// Injectors from wire.go:

func Up(ctx context.Context) (Dependencies, error) {
	configConfig, err := config.New()
	if err != nil {
		return Dependencies{}, err
	}
	client, err := NewEntClient(configConfig)
	if err != nil {
		return Dependencies{}, err
	}
	service := user.NewService(client, configConfig)
	taskService := task.NewService(client, configConfig)
	tagService := tag.NewService(client)
	dependencies := NewDependencies(configConfig, client, service, taskService, tagService)
	return dependencies, nil
}
